import type {
  SalesActivity,
  SalesCalendarEvent,
  SalesCustomer,
  SalesDeal,
  SalesLead,
  SalesNote,
  SalesPipelineStage,
  SalesTask,
} from '@/lib/sales/types';

export const SALES_REFERENCE_DATE = '2026-04-14T09:00:00-04:00';

export const salesPipelineStages: SalesPipelineStage[] = [
  'new_lead',
  'contacted',
  'replied',
  'discovery_scheduled',
  'discovery_completed',
  'qualified',
  'demo_scheduled',
  'demo_completed',
  'proposal_sent',
  'negotiation',
  'won',
  'lost',
  'nurture',
];

export const salesStageLabels: Record<SalesPipelineStage, string> = {
  new_lead: 'New Lead',
  contacted: 'Contacted',
  replied: 'Replied',
  discovery_scheduled: 'Discovery Scheduled',
  discovery_completed: 'Discovery Completed',
  qualified: 'Qualified',
  demo_scheduled: 'Demo Scheduled',
  demo_completed: 'Demo Completed',
  proposal_sent: 'Proposal Sent',
  negotiation: 'Negotiation',
  won: 'Won',
  lost: 'Lost',
  nurture: 'Nurture',
};

export const salesLeads: SalesLead[] = [
  {
    id: 'lead-101',
    companyName: 'Gestion Martel',
    contactPerson: 'Mylene Martel',
    phone: '514-555-1101',
    email: 'mylene@gestionmartel.ca',
    source: 'referral',
    propertyType: 'small_multifamily',
    unitCount: 18,
    city: 'Montreal',
    ownerType: 'property_manager',
    notes: 'Losing too much time answering duplicated inquiry messages across multiple vacancies.',
    assignedRep: 'Anthony',
    status: 'qualified',
    lastContactDate: '2026-04-13',
    nextFollowUpDate: '2026-04-16',
    estimatedFit: 'high',
    linkedDealId: 'deal-301',
    createdAt: '2026-04-02',
  },
  {
    id: 'lead-102',
    companyName: 'Immeubles Leroux',
    contactPerson: 'Philippe Leroux',
    phone: '438-555-1102',
    email: 'philippe@immeublesleroux.ca',
    source: 'website',
    propertyType: 'triplex',
    unitCount: 6,
    city: 'Laval',
    ownerType: 'landlord',
    notes: 'Interested in getting fewer unqualified applicants and faster first-response coverage.',
    assignedRep: 'Anthony',
    status: 'discovery_scheduled',
    lastContactDate: '2026-04-12',
    nextFollowUpDate: '2026-04-14',
    estimatedFit: 'high',
    linkedDealId: 'deal-302',
    createdAt: '2026-04-05',
  },
  {
    id: 'lead-103',
    companyName: 'Boreal Capital',
    contactPerson: 'Samuel Kim',
    phone: '514-555-1103',
    email: 'samuel@borealcapital.ca',
    source: 'linkedin',
    propertyType: 'large_multifamily',
    unitCount: 74,
    city: 'Longueuil',
    ownerType: 'portfolio_owner',
    notes: 'Curious about structured intake, SLA coverage, and how FluxLocatif differs from a leasing agency.',
    assignedRep: 'Anthony',
    status: 'proposal_sent',
    lastContactDate: '2026-04-11',
    nextFollowUpDate: '2026-04-15',
    estimatedFit: 'high',
    linkedDealId: 'deal-303',
    createdAt: '2026-03-26',
  },
  {
    id: 'lead-104',
    companyName: 'Patrimoine Cote Nord',
    contactPerson: 'Ariane Gagnon',
    phone: '581-555-1104',
    email: 'ariane@patrimoinecotenord.ca',
    source: 'partner',
    propertyType: 'mixed_use',
    unitCount: 33,
    city: 'Quebec City',
    ownerType: 'investor',
    notes: 'Needs better prequalification before booking visits. Concerned about maintaining premium tenant quality.',
    assignedRep: 'Anthony',
    status: 'demo_completed',
    lastContactDate: '2026-04-10',
    nextFollowUpDate: '2026-04-17',
    estimatedFit: 'medium',
    linkedDealId: 'deal-304',
    createdAt: '2026-04-01',
  },
  {
    id: 'lead-105',
    companyName: 'NOVA Gestion Locative',
    contactPerson: 'Jeremy Hall',
    phone: '514-555-1105',
    email: 'jeremy@novagestion.ca',
    source: 'cold_outreach',
    propertyType: 'condo_portfolio',
    unitCount: 22,
    city: 'Montreal',
    ownerType: 'property_manager',
    notes: 'Replied to outreach and wants an overview of pricing before a call.',
    assignedRep: 'Anthony',
    status: 'replied',
    lastContactDate: '2026-04-09',
    nextFollowUpDate: '2026-04-14',
    estimatedFit: 'medium',
    createdAt: '2026-04-07',
  },
  {
    id: 'lead-106',
    companyName: 'Orion Habitations',
    contactPerson: 'Fatima Benali',
    phone: '450-555-1106',
    email: 'fatima@orionhabitations.ca',
    source: 'google_ads',
    propertyType: 'small_multifamily',
    unitCount: 12,
    city: 'Brossard',
    ownerType: 'investor',
    notes: 'Still early. Wants to compare us to traditional brokers and understand onboarding lift.',
    assignedRep: 'Anthony',
    status: 'nurture',
    lastContactDate: '2026-04-06',
    nextFollowUpDate: '2026-04-21',
    estimatedFit: 'medium',
    createdAt: '2026-04-03',
  },
  {
    id: 'lead-107',
    companyName: 'Siena Holdings',
    contactPerson: 'Alexandre Roy',
    phone: '438-555-1107',
    email: 'alexandre@sienaholdings.ca',
    source: 'event',
    propertyType: 'large_multifamily',
    unitCount: 91,
    city: 'Sherbrooke',
    ownerType: 'portfolio_owner',
    notes: 'Big portfolio, but internal team is not aligned yet on adopting a new leasing support workflow.',
    assignedRep: 'Anthony',
    status: 'lost',
    lastContactDate: '2026-04-08',
    nextFollowUpDate: '2026-05-05',
    estimatedFit: 'high',
    linkedDealId: 'deal-305',
    createdAt: '2026-03-22',
  },
  {
    id: 'lead-108',
    companyName: 'Atelier du Parc',
    contactPerson: 'Stephanie Gobeil',
    phone: '514-555-1108',
    email: 'stephanie@atelierduparc.ca',
    source: 'website',
    propertyType: 'triplex',
    unitCount: 4,
    city: 'Montreal',
    ownerType: 'landlord',
    notes: 'New inbound inquiry after reading about reducing lead-handling time and prequalifying applicants.',
    assignedRep: 'Anthony',
    status: 'new_lead',
    lastContactDate: '2026-04-14',
    nextFollowUpDate: '2026-04-15',
    estimatedFit: 'medium',
    createdAt: '2026-04-14',
  },
  {
    id: 'lead-109',
    companyName: 'Mason Street PM',
    contactPerson: 'Connor Walsh',
    phone: '514-555-1109',
    email: 'connor@masonstreetpm.ca',
    source: 'cold_outreach',
    propertyType: 'small_multifamily',
    unitCount: 15,
    city: 'Montreal',
    ownerType: 'property_manager',
    notes: 'Outreach sequence started. No reply yet.',
    assignedRep: 'Future Sales Rep',
    status: 'contacted',
    lastContactDate: '2026-04-13',
    nextFollowUpDate: '2026-04-17',
    estimatedFit: 'medium',
    createdAt: '2026-04-10',
  },
];

export const salesDeals: SalesDeal[] = [
  {
    id: 'deal-301',
    dealName: 'Gestion Martel - Growth rollout',
    leadId: 'lead-101',
    expectedMonthlyValue: 1790,
    estimatedCloseDate: '2026-04-25',
    selectedPlan: 'Growth',
    closeProbability: 72,
    dealStage: 'qualified',
    objections: ['Needs clarity on onboarding workload', 'Asked for response-time commitments'],
    notes: 'High fit. Strong pain around inquiry overload and disorganized leasing follow-up.',
  },
  {
    id: 'deal-302',
    dealName: 'Immeubles Leroux - Starter pilot',
    leadId: 'lead-102',
    expectedMonthlyValue: 890,
    estimatedCloseDate: '2026-04-19',
    selectedPlan: 'Starter',
    closeProbability: 58,
    dealStage: 'discovery_scheduled',
    objections: ['Budget sensitivity', 'Wants proof on applicant quality improvement'],
    notes: 'Discovery booked. Position value against brokerage fees and owner time loss.',
  },
  {
    id: 'deal-303',
    dealName: 'Boreal Capital - Portfolio package',
    leadId: 'lead-103',
    expectedMonthlyValue: 3200,
    estimatedCloseDate: '2026-04-28',
    selectedPlan: 'Portfolio',
    closeProbability: 66,
    dealStage: 'proposal_sent',
    objections: ['Needs internal stakeholder sign-off', 'Asks about CRM reporting for ownership'],
    notes: 'Proposal sent with premium service framing and cost comparison vs agency outsourcing.',
  },
  {
    id: 'deal-304',
    dealName: 'Patrimoine Cote Nord - Growth bundle',
    leadId: 'lead-104',
    expectedMonthlyValue: 1540,
    estimatedCloseDate: '2026-05-02',
    selectedPlan: 'Growth',
    closeProbability: 48,
    dealStage: 'demo_completed',
    objections: ['Needs French sales collateral', 'Wants clarity on escalation path'],
    notes: 'Demo landed well. Needs a tailored proposal with operational boundaries explained clearly.',
  },
  {
    id: 'deal-305',
    dealName: 'Siena Holdings - Enterprise style pilot',
    leadId: 'lead-107',
    expectedMonthlyValue: 3800,
    estimatedCloseDate: '2026-04-12',
    selectedPlan: 'Portfolio',
    closeProbability: 0,
    dealStage: 'lost',
    objections: ['Preferred to keep leasing fully in-house this quarter'],
    notes: 'Lost for timing, not fit. Candidate for later nurture once vacancy volume rises again.',
  },
  {
    id: 'deal-306',
    dealName: 'Rive Nord Rentals - Growth',
    leadId: 'lead-110',
    expectedMonthlyValue: 1680,
    estimatedCloseDate: '2026-04-09',
    selectedPlan: 'Growth',
    closeProbability: 100,
    dealStage: 'won',
    objections: ['Needed legal clarification on service boundaries'],
    notes: 'Signed after proposal revision and clear differentiation from property management.',
  },
];

export const salesCustomers: SalesCustomer[] = [
  {
    id: 'cust-401',
    companyName: 'Rive Nord Rentals',
    primaryContact: 'Camille Blais',
    phone: '450-555-2101',
    email: 'camille@rivenordrentals.ca',
    city: 'Laval',
    ownerType: 'investor',
    propertyType: 'small_multifamily',
    unitCount: 29,
    plan: 'Growth',
    signedDate: '2026-04-09',
    monthlyRevenue: 1680,
    linkedLeadId: 'lead-110',
    linkedDealId: 'deal-306',
    notes: 'Recently signed. Wants first monthly review focused on lead response speed and qualified applicants.',
    health: 'healthy',
  },
  {
    id: 'cust-402',
    companyName: 'Metropole Gestion',
    primaryContact: 'Nadia Savoie',
    phone: '514-555-2102',
    email: 'nadia@metropoleg.ca',
    city: 'Montreal',
    ownerType: 'property_manager',
    propertyType: 'large_multifamily',
    unitCount: 54,
    plan: 'Portfolio',
    signedDate: '2026-03-20',
    monthlyRevenue: 2840,
    linkedLeadId: 'lead-111',
    linkedDealId: 'deal-307',
    notes: 'Expansion conversation planned for May if service metrics stay strong.',
    health: 'healthy',
  },
  {
    id: 'cust-403',
    companyName: 'Habitations Villeray',
    primaryContact: 'Louis Perron',
    phone: '514-555-2103',
    email: 'louis@habitationsvilleray.ca',
    city: 'Montreal',
    ownerType: 'landlord',
    propertyType: 'triplex',
    unitCount: 8,
    plan: 'Starter',
    signedDate: '2026-02-27',
    monthlyRevenue: 790,
    linkedLeadId: 'lead-112',
    linkedDealId: 'deal-308',
    notes: 'Healthy customer but sensitive to missed follow-up reminders.',
    health: 'watch',
  },
];

export const salesTasks: SalesTask[] = [
  {
    id: 'task-501',
    title: 'Follow up with Philippe on discovery prep',
    description: 'Confirm the discovery agenda and gather current vacancy volume before the call.',
    dueAt: '2026-04-14T11:30:00-04:00',
    status: 'open',
    priority: 'high',
    category: 'follow_up',
    assignedTo: 'Anthony',
    leadId: 'lead-102',
    dealId: 'deal-302',
  },
  {
    id: 'task-502',
    title: 'Send pricing recap to NOVA Gestion Locative',
    description: 'Share a concise plan comparison and position against brokerage commission costs.',
    dueAt: '2026-04-14T16:00:00-04:00',
    status: 'open',
    priority: 'medium',
    category: 'follow_up',
    assignedTo: 'Anthony',
    leadId: 'lead-105',
  },
  {
    id: 'task-503',
    title: 'Build tailored proposal for Patrimoine Cote Nord',
    description: 'Address prequalification workflow, quality controls, and service boundary objections.',
    dueAt: '2026-04-15T10:00:00-04:00',
    status: 'open',
    priority: 'high',
    category: 'meeting_prep',
    assignedTo: 'Anthony',
    leadId: 'lead-104',
    dealId: 'deal-304',
  },
  {
    id: 'task-504',
    title: 'Call back Siena Holdings next week',
    description: 'Nurture sequence task to reopen conversation if internal bandwidth changes.',
    dueAt: '2026-05-05T14:00:00-04:00',
    status: 'open',
    priority: 'low',
    category: 'follow_up',
    assignedTo: 'Future Sales Rep',
    leadId: 'lead-107',
    dealId: 'deal-305',
  },
  {
    id: 'task-505',
    title: 'Review proposal feedback from Boreal Capital',
    description: 'Prepare negotiation points for stakeholder call and pricing justification.',
    dueAt: '2026-04-13T15:00:00-04:00',
    status: 'open',
    priority: 'urgent',
    category: 'meeting_prep',
    assignedTo: 'Anthony',
    leadId: 'lead-103',
    dealId: 'deal-303',
  },
  {
    id: 'task-506',
    title: 'Book onboarding success review for Rive Nord Rentals',
    description: 'Create a post-signature checkpoint and confirm reporting expectations.',
    dueAt: '2026-04-18T09:30:00-04:00',
    status: 'open',
    priority: 'medium',
    category: 'onboarding',
    assignedTo: 'Anthony',
    customerId: 'cust-401',
  },
  {
    id: 'task-507',
    title: 'Reply to Atelier du Parc inbound lead',
    description: 'Acknowledge the inquiry and offer two discovery slots this week.',
    dueAt: '2026-04-14T13:00:00-04:00',
    status: 'open',
    priority: 'high',
    category: 'follow_up',
    assignedTo: 'Anthony',
    leadId: 'lead-108',
  },
];

export const salesActivities: SalesActivity[] = [
  {
    id: 'activity-601',
    type: 'proposal',
    title: 'Proposal sent to Boreal Capital',
    description: 'Sent tailored Portfolio proposal with cost comparison against agency leasing fees.',
    occurredAt: '2026-04-11T10:40:00-04:00',
    actor: 'Anthony',
    leadId: 'lead-103',
    dealId: 'deal-303',
  },
  {
    id: 'activity-602',
    type: 'meeting',
    title: 'Demo completed for Patrimoine Cote Nord',
    description: 'Showed structured leasing workflow, applicant filtering, and team handoff model.',
    occurredAt: '2026-04-10T14:00:00-04:00',
    actor: 'Anthony',
    leadId: 'lead-104',
    dealId: 'deal-304',
  },
  {
    id: 'activity-603',
    type: 'call',
    title: 'Discovery call booked with Immeubles Leroux',
    description: 'Discovery confirmed for April 15 at 09:30 with pricing concerns flagged.',
    occurredAt: '2026-04-12T16:15:00-04:00',
    actor: 'Anthony',
    leadId: 'lead-102',
    dealId: 'deal-302',
  },
  {
    id: 'activity-604',
    type: 'email',
    title: 'Outbound sequence to Mason Street PM',
    description: 'Sent first outreach focused on response speed, prequalification, and leasing pipeline visibility.',
    occurredAt: '2026-04-13T08:45:00-04:00',
    actor: 'Future Sales Rep',
    leadId: 'lead-109',
  },
  {
    id: 'activity-605',
    type: 'status_change',
    title: 'Rive Nord Rentals marked as won',
    description: 'Contract signed and onboarding handoff initiated.',
    occurredAt: '2026-04-09T17:20:00-04:00',
    actor: 'Anthony',
    customerId: 'cust-401',
    dealId: 'deal-306',
  },
  {
    id: 'activity-606',
    type: 'note',
    title: 'Objection captured for Gestion Martel',
    description: 'Lead wants clear assurance on how much time their team needs to invest after signing.',
    occurredAt: '2026-04-13T12:10:00-04:00',
    actor: 'Anthony',
    leadId: 'lead-101',
    dealId: 'deal-301',
  },
];

export const salesNotes: SalesNote[] = [
  {
    id: 'note-701',
    entityType: 'lead',
    entityId: 'lead-101',
    category: 'objection',
    title: 'Implementation concern',
    content: 'Mylene likes the process clarity but wants to avoid adding internal admin overhead during onboarding.',
    author: 'Anthony',
    createdAt: '2026-04-13T12:00:00-04:00',
    tags: ['onboarding', 'objection'],
  },
  {
    id: 'note-702',
    entityType: 'deal',
    entityId: 'deal-303',
    category: 'meeting_note',
    title: 'Stakeholder review prep',
    content: 'Need a one-page summary on how FluxLocatif improves applicant quality without acting as a full property manager.',
    author: 'Anthony',
    createdAt: '2026-04-11T11:15:00-04:00',
    tags: ['proposal', 'positioning'],
  },
  {
    id: 'note-703',
    entityType: 'lead',
    entityId: 'lead-102',
    category: 'call_note',
    title: 'Discovery goals',
    content: 'Focus on current listing response times, tenant screening friction, and why traditional agencies feel expensive.',
    author: 'Anthony',
    createdAt: '2026-04-12T16:25:00-04:00',
    tags: ['discovery'],
  },
  {
    id: 'note-704',
    entityType: 'customer',
    entityId: 'cust-401',
    category: 'customer_note',
    title: 'Early customer success signal',
    content: 'Camille wants weekly visibility into inquiries handled and applicant quality trends for the first month.',
    author: 'Anthony',
    createdAt: '2026-04-10T09:20:00-04:00',
    tags: ['customer', 'reporting'],
  },
  {
    id: 'note-705',
    entityType: 'lead',
    entityId: 'lead-104',
    category: 'follow_up_note',
    title: 'Proposal angle',
    content: 'Emphasize structured prequalification, reduced admin time, and premium renter filtering rather than generic automation.',
    author: 'Anthony',
    createdAt: '2026-04-10T15:05:00-04:00',
    tags: ['proposal', 'messaging'],
  },
];

export const salesCalendarEvents: SalesCalendarEvent[] = [
  {
    id: 'calendar-801',
    provider: 'google_calendar',
    title: 'Discovery call - Immeubles Leroux',
    description: 'Discovery call about inquiry handling load and applicant prequalification.',
    startsAt: '2026-04-15T09:30:00-04:00',
    endsAt: '2026-04-15T10:15:00-04:00',
    kind: 'discovery_call',
    status: 'scheduled',
    entityType: 'lead',
    entityId: 'lead-102',
    attendees: ['philippe@immeublesleroux.ca'],
    location: 'Google Meet',
    meetingUrl: 'https://meet.google.com/',
  },
  {
    id: 'calendar-802',
    provider: 'google_calendar',
    title: 'Demo follow-up - Patrimoine Cote Nord',
    description: 'Proposal review and next-step confirmation.',
    startsAt: '2026-04-17T11:00:00-04:00',
    endsAt: '2026-04-17T11:30:00-04:00',
    kind: 'follow_up',
    status: 'scheduled',
    entityType: 'lead',
    entityId: 'lead-104',
    attendees: ['ariane@patrimoinecotenord.ca'],
    location: 'Phone',
  },
  {
    id: 'calendar-803',
    provider: 'google_calendar',
    title: 'Boreal Capital proposal review',
    description: 'Negotiation call with operating partner and ownership lead.',
    startsAt: '2026-04-16T14:00:00-04:00',
    endsAt: '2026-04-16T14:45:00-04:00',
    kind: 'demo',
    status: 'scheduled',
    entityType: 'deal',
    entityId: 'deal-303',
    attendees: ['samuel@borealcapital.ca'],
    location: 'Google Meet',
    meetingUrl: 'https://meet.google.com/',
  },
  {
    id: 'calendar-804',
    provider: 'google_calendar',
    title: 'Customer kickoff check-in - Rive Nord Rentals',
    description: 'Early customer review with reporting expectations and onboarding milestones.',
    startsAt: '2026-04-18T09:30:00-04:00',
    endsAt: '2026-04-18T10:00:00-04:00',
    kind: 'task_reminder',
    status: 'pending_integration',
    entityType: 'customer',
    entityId: 'cust-401',
    attendees: ['camille@rivenordrentals.ca'],
  },
];

